### ISSUE TITLE
torrent unusable

### ISSUE THREAD

**Issue by liyijing024** [einanao/NFT-1M#1]
[ERROR] CUID#29 - Download aborted. URI=http://158.69.146.212:7777/announce?info_hash=%5C%D5%EB%D9%CD%C5%E0k1%01t%5D~%21~%C7%D8%B7r%BE&peer_id=A2-1-34-0-%DF%2BK%A29%DE%7C%60%F5c&uploaded=0&downloaded=0&left=89801138623&compact=1&key=K%A29%DE%7C%60%F5c&numwant=50&no_peer_id=1&port=6995&event=started&supportcrypto=1
Exception: [AbstractCommand.cc:856] errorCode=1 Failed to establish connection, cause: Connection timed out

**Comment by einanao** [comment]
Should work now
